version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling source code...
      - python manage.py makemigrations
      - python manage.py migrate
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"

